use mongodb::bson::oid::ObjectId;
use serde::{Deserialize, Serialize};

/// Entry in the database registered every minute while the computer is on.
#[derive(Debug, Serialize, Deserialize)]
pub struct Entry {
    /// Unique identifier for the entry. Optional and automatically generated by MongoDB.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    /// Timestamp of the entry. Automatically generated by the server.
    pub timestamp: String,
}
